import ReactMarkdown from "react-markdown";

export default function BRollViewer({ brollData, onReset }) {
  if (!brollData) return null;

  const cutsheet = brollData.cutsheet;
  if (!cutsheet) return null;

  const handleDownloadTXT = () => {
    const text = [
      `B-ROLL CUT SHEET — Generated by ${brollData.provider} (${brollData.model})`,
      "=".repeat(64),
      "",
      cutsheet,
      "",
      "=".repeat(64),
      `Tokens: ${brollData.input_tokens} input / ${brollData.output_tokens} output`,
      brollData.cost_usd != null ? `Cost: $${brollData.cost_usd.toFixed(4)}` : "",
    ].filter(Boolean).join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `broll_cutsheet_${brollData.job_id || "export"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(brollData, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `broll_cutsheet_${brollData.job_id || "export"}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="card card-gold fade-in">
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
        <h3 style={{ color: "var(--gold)", fontSize: 16, fontWeight: 600 }}>
          B-Roll Cut Sheet
        </h3>
        <span className="tag tag-success">GENERATED</span>
      </div>

      {/* Stats */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10, marginBottom: 18 }}>
        {[
          { label: "Provider", value: brollData.provider },
          { label: "Model", value: brollData.model?.split("-").slice(0, 2).join(" ") || brollData.model },
          {
            label: "Tokens",
            value: `${(brollData.input_tokens || 0).toLocaleString()} / ${(brollData.output_tokens || 0).toLocaleString()}`,
          },
          {
            label: "Cost",
            value: brollData.cost_usd != null ? `$${brollData.cost_usd.toFixed(4)}` : "—",
          },
        ].map((s) => (
          <div
            key={s.label}
            style={{
              background: "var(--bg-secondary)",
              borderRadius: 8,
              padding: "10px 12px",
              textAlign: "center",
            }}
          >
            <p style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2, textTransform: "uppercase", letterSpacing: "0.5px" }}>
              {s.label}
            </p>
            <p style={{ fontSize: 13, fontWeight: 700, color: "var(--gold)" }}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* B-Roll Cut Sheet Body (Markdown) */}
      <div
        style={{
          maxHeight: 520,
          overflowY: "auto",
          background: "var(--bg-secondary)",
          borderRadius: 10,
          padding: 20,
          marginBottom: 20,
          border: "1px solid var(--border-color)",
        }}
      >
        <div
          className="markdown-content"
          style={{
            fontSize: 12,
            lineHeight: 1.7,
            color: "var(--text-primary)",
          }}
        >
          <ReactMarkdown>{cutsheet}</ReactMarkdown>
        </div>
      </div>

      {/* Actions */}
      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>
        <button className="btn btn-outline" onClick={handleDownloadTXT}>
          Download TXT
        </button>
        <button className="btn btn-outline" onClick={handleDownloadJSON}>
          Download JSON
        </button>
        <button className="btn btn-gold" onClick={onReset} style={{ marginLeft: "auto" }}>
          Process New File
        </button>
      </div>
    </div>
  );
}
