import ReactMarkdown from "react-markdown";

export default function CutSheetViewer({ cutsheet, onReset }) {
  if (!cutsheet) return null;

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(cutsheet, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `cutsheet_${cutsheet.cutsheet_id || "export"}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadTXT = () => {
    const text = [
      `CUT SHEET — Generated by ${cutsheet.provider} (${cutsheet.model})`,
      "=".repeat(64),
      "",
      cutsheet.cutsheet,
      "",
      "=".repeat(64),
      `Tokens: ${cutsheet.input_tokens} input / ${cutsheet.output_tokens} output`,
      `Cost: $${cutsheet.cost_usd.toFixed(4)}`,
    ].join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `cutsheet_${cutsheet.cutsheet_id || "export"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="card card-gold fade-in">
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
        <h3 style={{ color: "var(--gold)", fontSize: 16, fontWeight: 600 }}>
          06 — Editor Cut Sheet
        </h3>
        <span className="tag tag-success">GENERATED</span>
      </div>

      {/* Stats */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10, marginBottom: 18 }}>
        {[
          { label: "Provider", value: cutsheet.provider },
          { label: "Model", value: cutsheet.model.split("-").slice(0, 2).join(" ") },
          {
            label: "Tokens",
            value: `${cutsheet.input_tokens.toLocaleString()} / ${cutsheet.output_tokens.toLocaleString()}`,
          },
          { label: "Cost", value: `$${cutsheet.cost_usd.toFixed(4)}` },
        ].map((s) => (
          <div
            key={s.label}
            style={{
              background: "var(--bg-secondary)",
              borderRadius: 8,
              padding: "10px 12px",
              textAlign: "center",
            }}
          >
            <p style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2, textTransform: "uppercase", letterSpacing: "0.5px" }}>
              {s.label}
            </p>
            <p style={{ fontSize: 13, fontWeight: 700, color: "var(--gold)" }}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* Cut Sheet Body */}
      <div
        style={{
          maxHeight: 520,
          overflowY: "auto",
          background: "var(--bg-secondary)",
          borderRadius: 10,
          padding: 22,
          marginBottom: 20,
          fontSize: 13,
          lineHeight: 1.7,
          color: "var(--text-primary)",
        }}
      >
        <div className="cutsheet-content">
          <ReactMarkdown>{cutsheet.cutsheet}</ReactMarkdown>
        </div>
      </div>

      {/* Actions */}
      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>
        <button className="btn btn-outline" onClick={handleDownloadJSON}>
          Download JSON
        </button>
        <button className="btn btn-outline" onClick={handleDownloadTXT}>
          Download TXT
        </button>
        <button className="btn btn-gold" onClick={onReset} style={{ marginLeft: "auto" }}>
          Process New File
        </button>
      </div>
    </div>
  );
}
