import json

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from ..config import TRANSCRIPTS_DIR, CUTSHEETS_DIR
from ..models import CutSheetRequest
from ..services.ai import generate_cutsheet, PRICING, DEFAULT_CUTSHEET_PROMPT

router = APIRouter(prefix="/api/generate", tags=["generate"])


# ── Model catalogue ──────────────────────────────────────────────────────────

@router.get("/models")
async def get_available_models():
    return {
        "anthropic": {
            "name": "Anthropic (Claude)",
            "models": [
                {"id": "claude-opus-4-6", "name": "Claude Opus 4.6 (Most Intelligent)", "recommended": True},
                {"id": "claude-sonnet-4-5", "name": "Claude Sonnet 4.5 (Balanced)", "recommended": False},
                {"id": "claude-haiku-4-5", "name": "Claude Haiku 4.5 (Fastest)", "recommended": False},
            ],
        },
        "openai": {
            "name": "OpenAI",
            "models": [
                {"id": "gpt-4o", "name": "GPT-4o (Latest)", "recommended": True},
                {"id": "gpt-4o-mini", "name": "GPT-4o Mini (Cheapest)", "recommended": False},
                {"id": "gpt-4-turbo", "name": "GPT-4 Turbo", "recommended": False},
            ],
        },
        "gemini": {
            "name": "Google (Gemini)",
            "models": [
                {"id": "gemini-2.0-flash", "name": "Gemini 2.0 Flash (Fastest)", "recommended": True},
                {"id": "gemini-1.5-pro", "name": "Gemini 1.5 Pro", "recommended": False},
                {"id": "gemini-2.0-pro", "name": "Gemini 2.0 Pro", "recommended": False},
            ],
        },
    }


@router.get("/pricing")
async def get_pricing():
    return PRICING


@router.get("/default-prompt")
async def get_default_prompt():
    return {"prompt": DEFAULT_CUTSHEET_PROMPT}


# ── Cut sheet generation ─────────────────────────────────────────────────────

def _format_time(seconds: float | None) -> str:
    if seconds is None:
        return "00:00:00.00"
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:05.2f}"


def _format_transcript_for_ai(transcript_data: dict) -> str:
    """Convert transcript JSON into readable timestamped text for the AI."""
    lines = []
    for sentence in transcript_data.get("sentences", []):
        start = _format_time(sentence.get("start"))
        end = _format_time(sentence.get("end"))
        speaker = sentence.get("speaker_name", "Unknown")
        text = sentence.get("text", "")
        lines.append(f"[{start} → {end}] {speaker}: {text}")
    return "\n".join(lines)


@router.post("/cutsheet")
async def create_cutsheet(request: CutSheetRequest):
    """Generate an editor cut sheet from a transcript using an AI model."""
    transcript_path = TRANSCRIPTS_DIR / f"{request.transcript_job_id}.json"
    if not transcript_path.exists():
        raise HTTPException(404, "Transcript not found. Run transcription first.")

    with open(transcript_path, encoding="utf-8") as f:
        transcript_data = json.load(f)

    transcript_text = _format_transcript_for_ai(transcript_data)

    try:
        result = await generate_cutsheet(
            transcript_text,
            request.provider,
            request.model,
            request.custom_prompt,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        raise HTTPException(500, f"AI generation error: {str(e)}")

    # Persist
    cutsheet_id = f"{request.transcript_job_id}_{request.provider}_{request.model.replace('-', '_')}"
    cutsheet_path = CUTSHEETS_DIR / f"{cutsheet_id}.json"
    result["cutsheet_id"] = cutsheet_id

    with open(cutsheet_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    return result


@router.get("/download/{cutsheet_id}")
async def download_cutsheet(cutsheet_id: str, format: str = "json"):
    """Download cut sheet as JSON or TXT."""
    cutsheet_path = CUTSHEETS_DIR / f"{cutsheet_id}.json"
    if not cutsheet_path.exists():
        raise HTTPException(404, "Cut sheet not found")

    if format == "txt":
        with open(cutsheet_path, encoding="utf-8") as f:
            data = json.load(f)
        txt_path = CUTSHEETS_DIR / f"{cutsheet_id}.txt"
        with open(txt_path, "w", encoding="utf-8") as f:
            f.write(f"CUT SHEET — Generated by {data['provider']} ({data['model']})\n")
            f.write("=" * 64 + "\n\n")
            f.write(data["cutsheet"])
            f.write(f"\n\n{'=' * 64}\n")
            f.write(f"Tokens: {data['input_tokens']} input / {data['output_tokens']} output\n")
            f.write(f"Cost: ${data['cost_usd']:.4f}\n")
        return FileResponse(txt_path, media_type="text/plain", filename=f"cutsheet_{cutsheet_id}.txt")

    return FileResponse(
        cutsheet_path,
        media_type="application/json",
        filename=f"cutsheet_{cutsheet_id}.json",
    )
